version: '3.4'
 
services:
  # flyway:
  #     image: flyway/flyway
  #     container_name: BPFlyway
  #     command: -url=jdbc:mysql://host.docker.internal:3307/breakpointDB -user=user -password=root -connectRetries=60 migrate
  #     volumes:
  #       - .:/flyway/sql/migrations
  #     depends_on:
  #       - db

  db:
    image: mysql:5.7
    container_name: Q3-breakpointDBcontainer
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'breakpointDB'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"

    networks:
    - mynetwork

  Q3-PHPMA:
    image: phpmyadmin/phpmyadmin
    container_name: BPPhpmyadmindb
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8080:80

  Q3-Backend:
    image: ${DOCKER_REGISTRY-}q3backend
    build:
      context: Q3-Concept.Server
      dockerfile: Q3-Concept.Server/Dockerfile

    environment:
      - ASPNETCORE_URLS=http://+:5000

    ports:
      - "5000:5000"

    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge