CREATE TABLE machine_monitoring_poorten (
  id int(11) NOT NULL AUTO_INCREMENT,
  board int(11) NOT NULL DEFAULT '0',
  port int(11) NOT NULL DEFAULT '0',
  name varchar(255) DEFAULT NULL,
  volgorde int(11) NOT NULL DEFAULT '0',
  visible tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id)
);

CREATE TABLE monitoring_data_202009 (
  id int(11) NOT NULL AUTO_INCREMENT,
  board tinyint(4) NOT NULL DEFAULT '0',
  port tinyint(4) NOT NULL DEFAULT '0',
  com tinyint(4) NOT NULL DEFAULT '0',
  code int(11) NOT NULL DEFAULT '0',
  code2 int(11) NOT NULL DEFAULT '0',
  timestamp datetime(6) DEFAULT NULL,
  datum date DEFAULT NULL,
  mac_address varchar(50) NOT NULL DEFAULT '',
  shot_time double(11,6) NOT NULL DEFAULT '0.000000',
  previous_shot_id int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY code (code),
  KEY timestamp (timestamp),
  KEY datum (datum),
  KEY board_port_datum (board,port,datum),
  KEY board (board),
  KEY port (port),
  KEY board_port (board,port)
);

CREATE TABLE production_data (
  id int(11) NOT NULL AUTO_INCREMENT,
  treeview_id int(11) NOT NULL DEFAULT '0',
  treeview2_id int(11) NOT NULL DEFAULT '0',
  start_date date DEFAULT NULL,
  start_time time NOT NULL DEFAULT '00:00:00',
  end_date date DEFAULT NULL,
  end_time time NOT NULL DEFAULT '00:00:00',
  amount double(11,2) NOT NULL DEFAULT '0.00',
  name varchar(255) NOT NULL DEFAULT '',
  description text NOT NULL,
  port tinyint(4) NOT NULL DEFAULT '0',
  board tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY treeview_id (treeview_id),
  KEY port (port),
  KEY board (board),
  KEY start_date_start_time (start_date,start_time),
  KEY end_date_end_time (end_date,end_time)
);

CREATE TABLE `treeview` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `object` char(1) NOT NULL DEFAULT '',
  `naam` varchar(255) NOT NULL DEFAULT '',
  `omschrijving` varchar(255) NOT NULL DEFAULT '',
  `boom_volgorde` int(11) NOT NULL DEFAULT '0',
  `stamkaart` mediumtext NOT NULL,
  `treeviewtype_id` int(11) NOT NULL DEFAULT '0',
  `serienummer` varchar(255) NOT NULL DEFAULT '',
  `bouwjaar` varchar(255) NOT NULL DEFAULT '',
  `actief` smallint(6) NOT NULL DEFAULT '1',
  `wijzigactief` int(11) NOT NULL DEFAULT '0',
  `vrijgegeven` smallint(6) NOT NULL DEFAULT '0',
  `installatiedatum` int(11) NOT NULL DEFAULT '0',
  `garantietot` int(11) NOT NULL DEFAULT '0',
  `aanschafwaarde` decimal(11,2) NOT NULL DEFAULT '0.00',
  `afschrijving` int(11) NOT NULL DEFAULT '0',
  `jaarafschrijving` int(11) NOT NULL DEFAULT '0',
  `afschrijvingeen` smallint(4) NOT NULL DEFAULT '0',
  `budgetvorig` decimal(11,2) NOT NULL DEFAULT '0.00',
  `budgetnu` decimal(11,2) NOT NULL DEFAULT '0.00',
  `melden` int(1) NOT NULL DEFAULT '1',
  `correctief` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Mag er op dit object correctief gemeld worden?',
  `werkopdracht` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Mag er op dit object een werkopdracht aangemaakt worden?',
  `fabrikanten_id` int(11) NOT NULL DEFAULT '0',
  `leverancieren_id` int(11) NOT NULL DEFAULT '0',
  `locaties_id` int(11) NOT NULL DEFAULT '0',
  `kostenplaats_id` int(11) NOT NULL DEFAULT '0',
  `parent` int(11) NOT NULL DEFAULT '0',
  `new_id` int(11) NOT NULL DEFAULT '0',
  `old_datum` date DEFAULT NULL,
  `treeviewtype` varchar(255) NOT NULL DEFAULT '',
  `keuringsinstantie_id` int(11) NOT NULL DEFAULT '0',
  `rie_nr` int(11) NOT NULL DEFAULT '0',
  `onderhoud` int(11) NOT NULL DEFAULT '0',
  `onderhoudstemplate` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Mag dit object worden opgenomen in een onderhoudstemplate?',
  `treeviewsoort_id` int(11) NOT NULL DEFAULT '0',
  `show_visual` tinyint(1) NOT NULL DEFAULT '0',
  `gecodeerd` varchar(65) NOT NULL DEFAULT '',
  `eigenaar_id` int(11) NOT NULL,
  `keuringsplichtig` int(11) NOT NULL,
  `laatstgeteld` date DEFAULT NULL,
  `onderhoudsbedrijf_id` int(6) NOT NULL COMMENT 'Derden - Voor onderhoud bedr.',
  `stamkaart_old` mediumtext,
  `objecttemplate_id` int(11) NOT NULL,
  `koppelrelatie_id` int(11) NOT NULL,
  `nlsfb2_id` int(11) NOT NULL,
  `vastgoed_aantal` decimal(11,2) NOT NULL,
  `vastgoed_eenheden_id` int(11) NOT NULL,
  `koppelpersoon_id` int(11) DEFAULT NULL,
  `koppelrelatie2_id` int(11) DEFAULT NULL,
  `koppelpersoon2_id` int(11) DEFAULT NULL,
  `medewerker_id` int(11) NOT NULL COMMENT 'personen_id ( Gemaakt voor Joulz 01-03-2012 )',
  `omschrijving_id` int(11) NOT NULL,
  `opgenomen_in_begroting` int(11) NOT NULL,
  `opgenomen_in_begroting_datum` datetime DEFAULT NULL,
  `uitleen_magazijn_id` int(11) NOT NULL,
  `uitleen_treeviewsoort_id` int(11) NOT NULL,
  `is_uitgeleend` int(1) NOT NULL,
  `uitleen_status` int(11) NOT NULL,
  `uitleenbaar` int(11) NOT NULL,
  `barcode` varchar(255) NOT NULL,
  `aangemaakt_op` datetime NOT NULL,
  `aangemaakt_door` varchar(255) NOT NULL,
  `nonactief_id` int(11) NOT NULL COMMENT 'Aparte status voor Joulz voor wanneer een object kapot is, of gestolen, etc.. 20-06-2013',
  `dragernr` varchar(255) NOT NULL,
  `stamkaarten_id` int(11) NOT NULL,
  `maat` varchar(255) NOT NULL,
  `deliveryaddress_number` int(11) NOT NULL,
  `deliveryaddress_name` varchar(255) NOT NULL,
  `kastnr` int(11) NOT NULL,
  `vak` int(11) NOT NULL,
  `datum_inbehandeling` date NOT NULL,
  `datum_laatste_wasbeurt` date NOT NULL,
  `kenteken` varchar(255) NOT NULL,
  `datum_uitleen` date NOT NULL,
  `geplande_datum_ontvangst` date NOT NULL,
  `datum_laatste_uitscan` date NOT NULL,
  `datum_aflevering` date NOT NULL,
  `laatste_tellerstand` double(11,2) NOT NULL COMMENT 'Wat was de tellerstand bij de laatste beurt voor de ingebruikname van dit object',
  `laatste_beurt_datum` date NOT NULL COMMENT 'Wanneer is de laatste beurt uitgevoerd voor ingebruikname van dit object.',
  `tellerstand_opgenomen` tinyint(1) NOT NULL COMMENT 'Dit geeft aan of de tellerstand al eens is opgegeven. M.a.w. moet er een aparte berekening worden uitgevoerd bij de opnamelijst.',
  `geaccepteerd` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'JOU-1: Is het object geaccepteerd als klant',
  `sweep_api` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Mogen er werkorders middels de SWEEP API ingeschoten worden voor dit object?',
  `laatste_beurt` int(11) NOT NULL COMMENT 'Dit is frequentie van de laatste beurt ',
  `laatste_servicebeurt_id` int(11) DEFAULT NULL COMMENT 'Welke servicebeurt is het laatste uitgevoerd voor ingebruikname van dit object',
  `hoofdprocessen_id` int(11) NOT NULL DEFAULT '0',
  `processtappen_id` int(11) NOT NULL DEFAULT '0',
  `machine_monitoringen_timeout_sec` int(11) NOT NULL DEFAULT '30',
  `toegang_type_id` int(11) NOT NULL DEFAULT '0',
  `extern_toegangsbeleid` tinyint(1) NOT NULL DEFAULT '0',
  `machine_monitoring_streef_cyclus_tijd` double(11,2) NOT NULL DEFAULT '0.00',
  `adres` varchar(255) NOT NULL DEFAULT '',
  `postcode` varchar(255) NOT NULL DEFAULT '',
  `plaats` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `fabrikanten_id` (`fabrikanten_id`),
  KEY `leverancieren_id` (`leverancieren_id`),
  KEY `locaties_id` (`locaties_id`),
  KEY `parent` (`parent`),
  KEY `naam` (`naam`),
  KEY `treeviewtype_id` (`treeviewtype_id`),
  KEY `bouwjaar` (`bouwjaar`),
  KEY `actief` (`actief`),
  KEY `wijzigactief` (`wijzigactief`),
  KEY `jaarafschrijving` (`jaarafschrijving`),
  KEY `kostenplaats_id` (`kostenplaats_id`),
  KEY `new_id` (`new_id`),
  KEY `keuringsinstantie_id` (`keuringsinstantie_id`),
  KEY `treeviewsoort_id` (`treeviewsoort_id`),
  KEY `serienummer` (`serienummer`),
  KEY `rie_nr` (`rie_nr`),
  KEY `show_visual` (`show_visual`),
  KEY `eigenaar_id` (`eigenaar_id`),
  KEY `keuringsplichtig` (`keuringsplichtig`),
  KEY `onderhoudsbedrijf_id` (`onderhoudsbedrijf_id`),
  KEY `koppelrelatie_id` (`koppelrelatie_id`),
  KEY `nlsfb2_id` (`nlsfb2_id`),
  KEY `vastgoed_eenheden_id` (`vastgoed_eenheden_id`),
  KEY `medewerker_id` (`medewerker_id`),
  KEY `omschrijving_id` (`omschrijving_id`),
  KEY `koppelpersoon_id` (`koppelpersoon_id`),
  KEY `koppelrelatie2_id` (`koppelrelatie2_id`),
  KEY `uitleen_magazijn_id` (`uitleen_magazijn_id`),
  KEY `uitleen_treeviewsoort_id` (`uitleen_treeviewsoort_id`),
  KEY `is_uitgeleend` (`is_uitgeleend`),
  KEY `hoofdprocessen_id` (`hoofdprocessen_id`),
  KEY `processtappen_id` (`processtappen_id`),
  KEY `toegang_type_id` (`toegang_type_id`)
);