name: Docker Image CI

on:
  push:
    branches: [ main, CICD/CD-Docker ]
  pull_request:
    branches: [ main, CICD/CD-Docker ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Build the Docker image
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      run: docker build --file ./Q3-Concept.Server/Q3-Concept.Server --tag my-image-name:$(date +%s)
      working-directory: ./Q3-Concept.Server/Q3-Concept.Server

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: uffiee1/q3concept
        tags: v1, latest
        registry: docker.io
        dockerfile: ./Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
